query HomeQuery($siteId: [QueryArgument]) {
  entry(section: "home", siteId: $siteId) {
    id
    ... on home_home_Entry {
      id
      hero {
        ... on hero_BlockType {
          id
          heading
          subheading
          backgroundText
          backgroundColour
        }
      }
      pageBuilder {
        ... on pageBuilder_contentSimple_BlockType {
          id
          typeHandle
          body
        }
        ... on pageBuilder_list_BlockType {
          id
          typeHandle
          heading
          backgroundColour
          listItem {
            ... on listItem_BlockType {
              id
              heading
              body
            }
          }
          backgroundColour
        }
        ... on pageBuilder_experience_BlockType {
          id
          typeHandle
          blockType
          heading
          positions {
            ... on experience_experience_Entry {
              id
              title
              experience {
                ... on experience_BlockType {
                  id
                  position
                  location
                  description
                }
              }
            }
          }
        }
        ... on pageBuilder_contact_BlockType {
          id
          typeHandle
          heading
        }
      }
    }
  }
}