query Entry($siteId: [QueryArgument]) {
  entry(section: "home", siteId: $siteId) {
    id
    ... on home_home_Entry {
      id
      hero {
        ... on hero_BlockType {
          id
          heading
          subheading
          backgroundText
          backgroundColour
        }
      }
      projectsGallery {
        ... on projectsGallery_project_BlockType {
          id
          entries {
            ... on projects_projects_Entry {
              id
              title
              imageAsset {
                url
                title
              }
            }
          }
          dualVariation
        }
      }
      projects {
        ... on projects_projects_Entry {
          id
          title
          private
        }
      }
    }
  }
}
